# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from mainWindow import Ui_MainWindow
import pymysql

class up:
    def __init__(self):
        db=pymysql.connect("host","user","password","database")
        cursor=db.cursor()
        cursor.execute("select username,password from table")
        self.data = cursor.fetchone()
        db.close()


class login_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.account = QtWidgets.QLabel(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(250, 122, 41, 16))
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(210, 40, 371, 20))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.account.setFont(font)
        self.account.setObjectName("account")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(250, 182, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.account_input = QtWidgets.QLineEdit(self.centralwidget)
        self.account_input.setGeometry(QtCore.QRect(300, 120, 211, 21))
        self.account_input.setText("")
        self.account_input.setObjectName("account_input")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(300, 180, 211, 21))
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(250, 250, 75, 23))
        self.confirm.setObjectName("confirm")
        self.confirm.clicked.connect(self.click_confirm)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.click_cancel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "采购单补全修正程序"))
        self.account.setText(_translate("MainWindow", "账号："))
        self.password.setText(_translate("MainWindow", "密码："))
        self.account_input.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.confirm.setText(_translate("MainWindow", "登录"))
        self.pushButton.setText(_translate("MainWindow", "退出"))
        self.title.setText(_translate("MainWindow", "请输入账号和密码"))

    def click_confirm(self):
        self.confirm.setDisabled(True)
        up1 = up()
        global user_password
        user_password = up1.data
        if self.account_input.text().strip()== user_password[0] and self.password_input.text().strip() == user_password[1]:
            # QtWidgets.QApplication.instance().quit()
            self.title.setText("登录成功！")
            self.form2 = QtWidgets.QMainWindow()
            self.ui2 = Ui_MainWindow()
            self.ui2.setupUi(self.form2)
            self.form2.show()
        else:
            self.confirm.setEnabled(True)
            self.title.setText("账号或密码错误！")

    def click_cancel(self):
        QtWidgets.QApplication.instance().quit()

def showWindow():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = login_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    showWindow()
